<div class="row">
    <div class="col-12">
        <h5>CSE421 Term Project</h5>
        <h2>iDB - Smart Factory System</h2>

        <p>This project is done in UNIST CSE421 Database Systems Class. <a href="https://github.com/unistcse421/iDB" target="_blank">GitHub Link</a></p>

        <p>Our project topic is making a monitoring system for smart factory.</p>
        <ul>
            <li>Data acquisition from machine using microcontroller.</li>
            <li>Store the data in database management system.</li>
            <li>User can monitor the data via web based dashboard monitoring system</li>
            <li>User can control the data they want to see and find useful information from data visualization.</li>
            <li>Send the report regularly to the user via e-mail.</li>
        </ul>
    </div>
</div>
