<div class="row">
    <div class="col-4 push-4 pull-4">
        <h2>
            Forgot Password?
        </h2>
        <form action="<?=PROCESS?>/identify.php" method="post">
            <div class="field">
                <input type="email" name="email" placeholder="E-mail address" title="E-mail address">
            </div>
            <button type="submit">Send E-mail</button>
        </form>
    </div>
</div>
