<div class="row">
    <div class="col-12">
        <div>
            <h2>Machine Management</h2>
            <ul>
                <li><a href="#">Create a Machine</a></li>
            </ul>
        </div>
        <div>
            <h2>Report Management</h2>
            <ul>
                <li><a href="#">Create a Report</a></li>
            </ul>
        </div>
        <div>
            <h2>Account Management</h2>
            <ul>
                <li><button onclick="change_password();">Change Password</button></li>
                <li><button onclick="delete_account();">Delete Account</button></li>
            </ul>
        </div>
    </div>
</div>
