<header id="header">
    <h4><a href="<?=$this->HTML_ROOT?>"><?=$this->title?></a></h4>
    <h1><?=$this->header?></h1>
    <nav id="nav">
        <ul class="menu">
            <li class="item"><a href="<?=$this->HTML_ROOT?>?page=about">About iDB</a></li>
        </ul>
        <ul class="menu">
            <li class="item"><a href="<?=$this->HTML_ROOT?>?page=monitor">Monitor</a></li>
        </ul>
        <ul class="menu">
            <li class="item"><a href="<?=$this->HTML_ROOT?>?page=sign_in">Sign In</a></li>
            <!--<li class="item"><a href="<?=$this->HTML_ROOT?>?page=sign_up">Sign Up</a></li>-->
            <!--<li class="item"><a href="<?=$this->PAGE?>/logout.php">Log Out</a></li>-->
        </ul>
    </nav>
</header>
