<nav id="nav">
    <ul class="menu">
        <li class="item"><a href="<?=$this->HTML_ROOT?>">Home</a></li>
        <li class="item"><a href="<?=$this->HTML_ROOT?>?page=about">About iDB</a></li>
        <li class="item"><a href="<?=$this->HTML_ROOT?>?page=dashboard">Dashboard</a></li>
        <li class="item"><a href="<?=$this->HTML_ROOT?>?page=setting">Setting</a></li>
    </ul>
    <ul class="menu">
        <li class="item"><a href="<?=$this->PAGE?>/sign_out.php">Log Out</a></li>
    </ul>
</nav>
